### ISSUE TITLE
Link to File Upload broken if it contains Exotic Characters

### ISSUE THREAD

**Issue by MaisiKoleni** [ls1intum/Artemis#1050]
### Describe the bug
If files are uploaded with unusual characters such as – (en dash) in the file name, the link for downloading the submission (at least from the student's perspective) is broken. 

#### To Reproduce
1. Create a file upload excercise
2. Upload a file with em dash or other exotic chars and submit
3. View your Submission
4. Click on download file
5. The link should not work

#### Expected behavior
The submission is shown/downloaded.

#### Screenshots
![image](https://user-images.githubusercontent.com/11130248/68597107-aea9e300-049c-11ea-8ba2-333ce5be9218.png)

### Environment
**Does the download work on... ?**

_OS Windows 10:_
 - Google Chrome (78.0.3904.97) `DOES NOT WORK`
 - Vivaldi (2.8.1664.40) `DOES NOT WORK`
 - Firefox (68.0.2) `WORKS`
 - Microsoft Edge (44.18362.387.0) `WORKS`

_OS Android 9:_
 - Google Chrome (78.0.3904.96) `DOES NOT WORK`
 - Vivaldi (2.7.1624.277) `DOES NOT WORK`
 - Firefox (68.2.0) `WORKS`

#### Additional context
Submission location: artemis.ase.in.tum.de/api/files/file-upload-exercises/769/submissions/452148/Deckblatt–AfI.pdf

This (and maybe some problems connected to this) also happened to some students after submitting their homwork as well as to some tutors grading the homework.

// _Updated the system environment details as they are more important than initially thought._

**Comment by krusche** [comment]
We tested this on all supported browser. This seems to be an issue only for Vivaldi.
Please use a different browser in this case. We might fix this, but we cannot verify this with exotic browser environments.

**Comment by MaisiKoleni** [comment]
I can now confirm that the Problem _does not exist_ for Firefox (68.0.2, Win 10) on my PC.
However, the current Google Chrome Version 78.0.3904.97 (Offizieller Build) (64-Bit), Windows 10
and Google Chrome Version 78.0.3904.96 for Android 9 also have this problem.

**Comment by krusche** [comment]
Ok, then it seems that more browsers have this issue. We will try to normalize this URL so that the problem.
@ungaralex could you add url normalization here?

**Comment by 13XxM1CHA3lxX37** [comment]
Update:
We got this problem for multiple submissions and were informed by tutors that they could not view or download the file they should review. As we got all submissions from the Artemis team we could check for which submissions/filenames this applies (in the CSV file):

### These can't be opened at all
i.e. one clicks on "Submission File" it seems to open a new tab but it closes instantly

https://artemis.ase.in.tum.de/#/file-upload-exercise/770/submission/469045/assessment
469045;"/api/files/file-upload-exercises/770/submissions/469045/C:\Users\Baraa\Desktop\PGDP\Syntaxbaum.pdf";

https://artemis.ase.in.tum.de/#/file-upload-exercise/770/submission/460195/assessment
460195;"/api/files/file-upload-exercises/769/submissions/460195/C:\Users\49151\Desktop\PGDP\Übungsfolien\Scan2019-11-0917.16.03HausaufgabePGDPPinguinreihe.pdf";

https://artemis.ase.in.tum.de/#/file-upload-exercise/770/submission/439091/assessment
439091;"/api/files/file-upload-exercises/770/submissions/439091/C:\Users\erick\Documents\TUM\5.Semester\PGdP\Syntaxbaumwurzel.pdf";

https://artemis.ase.in.tum.de/#/file-upload-exercise/770/submission/460189/assessment
460189;"/api/files/file-upload-exercises/770/submissions/460189/C:\Users\49151\Desktop\PGDP\Übungsfolien\Scan2019-11-0917.09.14HausaufgabePGDPSynthaxbaum.pdf";

https://artemis.ase.in.tum.de/#/file-upload-exercise/770/submission/469040/assessment
469040;"/api/files/file-upload-exercises/769/submissions/469040/C:\Users\Baraa\Desktop\PGDP\Pinguinreihen.pdf";

https://artemis.ase.in.tum.de/#/file-upload-exercise/769/submission/439099/assessment
439099;"/api/files/file-upload-exercises/769/submissions/439099/C:\Users\erick\Documents\TUM\5.Semester\PGdP\Niugnip.jpg";

https://artemis.ase.in.tum.de/#/file-upload-exercise/769/submission/414483/assessment
414483;"/api/files/file-upload-exercises/769/submissions/414483/C:\Users\laeti\Desktop\UNI\pgdp\Pinguinreihe.jpg";


### Here at least a new Tab is opened
but the "website cannot be reached" error is shown along with the url

https://artemis.ase.in.tum.de/#/file-upload-exercise/770/submission/467771/assessment
467771;"/api/files/file-upload-exercises/769/submissions/467771/Aufgabe-w03-h02—Pinguinreihen.pdf";"ge75qav"

https://artemis.ase.in.tum.de/#/file-upload-exercise/770/submission/460464/assessment
https://artemis.ase.in.tum.de/api/files/file-upload-exercises/769/submissions/460464/Woche03H02PinguinreihenGrubmu%CC%88ller.pdf

https://artemis.ase.in.tum.de/#/file-upload-exercise/770/submission/458638/assessment
https://artemis.ase.in.tum.de/api/files/file-upload-exercises/769/submissions/458638/PinguinReihe-Regula%CC%88rerAusdruck.pdf

https://artemis.ase.in.tum.de/#/file-upload-exercise/770/submission/427447/assessment
https://artemis.ase.in.tum.de/api/files/file-upload-exercises/769/submissions/427447/Woche03H02-Pinguinreihen-NiklasClu%CC%88sserath.pdf

https://artemis.ase.in.tum.de/#/file-upload-exercise/770/submission/443229/assessment
443229;https://artemis.ase.in.tum.de/api/files/file-upload-exercises/769/submissions/443229/PGDPWoche03Hausaufgabe02–ReguläreAusdrücke.pdf

### Here one gets a 401 Api error
https://artemis.ase.in.tum.de/#/file-upload-exercise/770/submission/454407/assessment
454407;"/api/files/file-upload-exercises/770/submissions/454407/syntaxBaumAbgabe#.PNG";
{"type":"https://www.jhipster.tech/problem/problem-with-message","title":"Unauthorized","status":401,"detail":"Full authentication is required to access this resource","path":"/api/files/file-upload-exercises/770/submissions/454407/syntaxBaumAbgabe","message":"error.http.401"}

**Comment by MaisiKoleni** [comment]
> Update:
> We got this problem for multiple submissions and were informed by tutors that they could not view or download the file they should review.

I should add that in many cases the browser is not important anymore, it won't work, even for Firefox.

> Here at least a new Tab is opened

Only here switching the browser (e.g. to Firefox) works, because the problem are only the exotic characters in the filename.

**Comment by krusche** [comment]
I investigated the issue. Seems the full Windows path was used for students with Windows and Microsoft Edge as browser :-( 

I found less than 10 entries with 'C:' in the database and fixed them manually in the filesystem and the database.

I implemented a bugfix consisting of 2 improvements:
1) We normalize the URL on the client side. This should solve most problems for existing file submissions with non ascii characters that need to be encoded in a URL

2) We now handle wrongly formatted filenames on the server side:
a) In case of windows paths, we only take the last element, i.e. the correct file name
b) we remove all illegal characters, i.e. everything except `A-Z`, `a-z`, `0-9` and `.` and `-`
c) In case the filename gets too short, i.e. less than 5 characters including the file extension (e.g. a file called `ßßß.pdf`), we prepend 'file' to make sure the filename has entries before the file extension (e.g. `ßßß.pdf` --> `file.pdf`)

We need to verify this during testing and will deploy this with the next release.

Let me know if you find additional cases that are not covered in the 2 improvements above and feel free to reopen the issue then.

**Comment by 13XxM1CHA3lxX37** [comment]
The files with backslash can now be opened, but for files with "website cannot be reached" the error still persists. i.e. these submissions:

Problem: English Dash
https://artemis.ase.in.tum.de/#/file-upload-exercise/770/submission/467771/assessment

Problem: Umlaut?
https://artemis.ase.in.tum.de/#/file-upload-exercise/770/submission/460464/assessment
https://artemis.ase.in.tum.de/#/file-upload-exercise/770/submission/458638/assessment
https://artemis.ase.in.tum.de/#/file-upload-exercise/770/submission/427447/assessment
https://artemis.ase.in.tum.de/#/file-upload-exercise/770/submission/443229/assessment

**Comment by krusche** [comment]
The changes have not yet been deployed. We plan to deploy it tonight after some additional testing.

**Comment by 13XxM1CHA3lxX37** [comment]
Suggestion would be to use this regex [^\x00-\x7F]

**Comment by krusche** [comment]
We have a even stricter one, so this should be fine

**Comment by 13XxM1CHA3lxX37** [comment]
The new fix doesn't seem to work in Chrome and Safari, but only in Firefox.

See example
https://artemis.ase.in.tum.de/#/file-upload-exercise/770/submission/458638/assessment

![Снимок экрана 2019-11-22 в 14 19 30](https://user-images.githubusercontent.com/20713070/69429269-75dafb00-0d33-11ea-8fdb-581b69d8ec6f.png)
![Снимок экрана 2019-11-22 в 14 20 17](https://user-images.githubusercontent.com/20713070/69429278-7b384580-0d33-11ea-82ec-b938c8dd379c.png)
![Снимок экрана 2019-11-22 в 14 19 44](https://user-images.githubusercontent.com/20713070/69429272-78d5eb80-0d33-11ea-852c-d271562b2195.png)

![Снимок экрана 2019-11-22 в 14 23 34](https://user-images.githubusercontent.com/20713070/69429377-b0449800-0d33-11ea-9316-2cd8e73f89b7.png)

**Comment by krusche** [comment]
I get the same error, but I do not understand why. I tested it again locally and on our test server and it works correctly in Chrome. It might be an encoding problem. Maybe the file was uploaded on a Windows machine with a different encoding than our server is used to and now the problematic `ä` is differently encoded.

The good thing is, in the future there won't be such problem because we replace such characters.

Would be great if you can use Firefox in such cases for now, because it would be really hard for us to fix the problem
