### ISSUE TITLE
Sample solution view error in Quiz element drag and drop question

### ISSUE THREAD

**Issue by raffifasaro** [ls1intum/Artemis#10675]
### Describe the bug

The elements of the graphical sample solution are zoomed in and not fully visible. They are also not compatible with dark mode.

### To Reproduce

1. Go to quiz example question with UML diagram drag and drop
2. Click on 'show example solution' after quiz ended

### Expected behavior

Drag and drop elements for sample solution are formatted correctly for sample solution boxes and fully visible.

### Screenshots

<img width="1164" alt="Image" src="https://github.com/user-attachments/assets/35046450-2156-4928-b0b3-6510ac37cb42" />

<img width="1161" alt="Image" src="https://github.com/user-attachments/assets/e0ffa077-3901-4347-bcef-3ae5c275b261" />

### Which version of Artemis are you seeing the problem on?

8.0.0

### What browsers are you seeing the problem on?

Safari

### Relevant log output

```shell

```

**Comment by MoritzSpengler** [comment]
PNG scaling works in Artemis. 
Problem: 
The SVG boundaries in Petri Net diagrams do not account for text dimensions. As a result, text elements placed outside the visible area of their parent SVG are clipped, especially noticeable when the diagram is converted to PNG.
![Image](https://github.com/user-attachments/assets/2e7e1009-a602-4b17-bb31-606b252f354f)

![Image](https://github.com/user-attachments/assets/c7b41aa7-7c24-4c82-b3d8-cb97373f8a63)

**Comment by lana-ati** [comment]
<img width="1236" height="664" alt="Image" src="https://github.com/user-attachments/assets/472e10c9-71df-49c4-968d-21d3fece432f" />

Tested on Safari, the images seem to be fully displayed in the sample solution. Therefore I think this issue has been solved.

**Comment by konrad2002** [comment]
This still happens with 8.6.4

<img width="2272" height="768" alt="Image" src="https://github.com/user-attachments/assets/8c65e302-b4c3-4fde-bfc9-2bb5b35c204e" />

@lana-ati are you sure that you used a petri net in apollon?
