### ISSUE TITLE
Misleading Response/Status for Edge Case (0 of 0 Points)

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#3333]
### Describe the bug

Recently we created a programming exercise that had only test cases for "after due date".
Unfortunately, we got student reports because of the Artemis response for the submitted solutions.
This response is shown in the following picture in the screenshot section.
 
It looks like the mechanisms that decide whether a submission is displayed as "green" or "red" choose to be red in the edge case of "0 out of 0 points". In this edge case, however, the result should be green as long as the code compiles at least. Otherwise it will confuse the students. Another case is described in https://github.com/ls1intum/Artemis/issues/3333#issuecomment-830413583 .

After @krusche and I talked, we considered the following:

1. Preliminary must always be displayed (also in zero points case --> bugfix)
2. Preliminary must always be clickable (so that you can see more information in the details window, the explanation for preliminary should be visible here immediately, without extra hover)
3. Change color of preliminary to grey (like in the instructions)
4. Change icon of preliminary from (X) to (?)

#### To Reproduce

1. Create a programming exercise **with manual assessment and static code analysis 0% penalty** and set all test cases (in grading) to after due date. 
2. Create a compilable (or even the correct) solution
3. See the red X

#### Expected behavior

@krusche and I talked and decided: 
1. Preliminary must always be displayed (also in zero points case --> bugfix)
2. Preliminary must always be clickable (so that you can see more information in the details window, the explanation for preliminary should be visible here immediately, without extra hover)
3. Change color of preliminary to grey (like in the instructions)
4. Change icon of preliminary from (X) to (?)

#### Screenshots

0 of 0 Points:
![image](https://user-images.githubusercontent.com/22198798/116755016-0b3eec00-aa0a-11eb-910c-de0f99904adb.png)

1 of 1 Test ok (but not 100% Points) (should also be green from our point of view)
![image](https://user-images.githubusercontent.com/22198798/116756483-7c7f9e80-aa0c-11eb-9fa7-79c87e6cebd9.png)

### Environment

Artemis 4.11.8

**Comment by dfuchss** [comment]
@gstuer @LDAP JFYI I've create the issue regarding the 0 of 0 edge case

**Comment by dfuchss** [comment]
Some addition:
We think that the message shall be green iff all points that can be seen by the students have been reached.
So that it might be possible to have a green submission before the due date and after the due date (when the "after due date" test cases have run) the submission might change to a "red" submission.

The current behavior might be misleading to the students as "red" indicates that something is wrong. E.g. I've create a Public (Always visible) Test that has a weight of "1" and I have created an "after due date" test with the weight "99" .. the student now sees the following artemis response (even if he/she has the perfect solution)

![image](https://user-images.githubusercontent.com/22198798/116756483-7c7f9e80-aa0c-11eb-9fa7-79c87e6cebd9.png)

I think (as mentioned above) that this should be green (with the label preliminary) as this would indicate that as far as tested publicly the submission is ok.

**Comment by GeneralMine** [comment]
@JohannesStoehr looks like your green `Build Successful` could be used here, instead of `0 of 0 passed`.
So it may already be fixed here #3293 or what do you think Johannes?

**Comment by krusche** [comment]
> I think (as mentioned above) that this should be green (with the label preliminary) as this would indicate that as far as tested publicly the submission is ok.

I think this is a difficult trade-off. Artemis was envisioned in a way that students get immediate feedback without any hidden tests and in all my courses, we do not use hidden test. But I see the point of hidden tests for courses in which the grade is created based on the exercises and in exams.

Until know, the idea was that the result is only green when the student has reached at least 80% of the final score. We introduced the term `preliminary` to communicate to the student that additional tests or manual assessment will be executed after the deadline to address the issue that the student cannot reach 100%.

I think it would be misleading to show a green status, if the student has not reached a certain score (e.g. at least 80%) and if the result can turn red after the deadline. However we cannot completely avoid this case if manual assessment is activated.

I guess we now have too many different possible states in the result string and color and it's really difficult to find an easy and intuitive model that is not in some sense confusing.

I suggest we use this issue to brainstorm a little bit. I am a big fan of keeping things simple. Maybe we can come up with something simple which is intuitive and which reflects the status in a better way.

**Comment by dfuchss** [comment]
@GeneralMine thanks for the pointer. So maybe the edge case will be solved in 4.11.9 :)

**Comment by dfuchss** [comment]
@krusche I've illustrated a possible "decision tree" and a "definition" of green as a first proposal:

![image](https://user-images.githubusercontent.com/22198798/116778685-a5874a00-aa73-11eb-87e5-90b8a430a8fa.png)

As you can see the important decisions in the tree are regarding the due date (as this effects the visibility of test cases)
What do you all think about this behavior (and the "definition" of green)?
Would that be suitable for all current possibilities or is anything missing so far :)

**Comment by dfuchss** [comment]
Regarding the definition of green in case (1) and (3) I'm still not sure whether the indicator should only use the state of the test cases or the actual points .. in general we could also define green as X of X tests are green .. and do not use the points to decide the color. 

Actually, I think that would be the best. But in the picture I tried to reuse most of the current behavior :)

**Comment by dfuchss** [comment]
In general the problem with "red" is that students may understand this as "I've done something wrong" which is not the case here .. therefore, it might help to mark the submission as green based on the state the student can see. (with some remark that this might change if manual assessment or after-due-date test cases will taken into account)

**Comment by krusche** [comment]
Case 2 is definitely more complex as you show it. There are many exercises without hidden tests and those should definitely show a percentage.

I think this is also an important strength of Artemis that it always shows the (estimated) percentage of the Score to give an indication how much of the solution has been solved. I would argue that we should keep this.

I agree however that - only in the case of hidden tests - students should be able to evaluate whether they have successfully solved all "visible" tests or not.

We probably need to explain and visualize this in the result details dialog, because it's too difficult to encode this information in just one result string.

One potential solution could also be to use a gray color in case there are hidden tests, because the final status is simply not known yet

**Comment by dfuchss** [comment]
@krusche I agree on your points. The estimated percentage is a good indicator for the students as it shows that there might be more test cases that are some kind of not known before due date. So the percentage of all points might be helpful.

I also think that your proposed potential solution would be a good one for now.
Another point to think of would be the actual symbol in this case (maybe a question mark in a circle ? as it would indicate the absence of knowledge regarding the final status ?)

**Comment by dfuchss** [comment]
After @krusche and I talked, we considered the following (also edited in the description):

1. Preliminary must always be displayed (also in zero points case --> bugfix)
2. Preliminary must always be clickable (so that you can see more information in the details window, the explanation for preliminary should be visible here immediately, without extra hover)
3. Change color of preliminary to grey (like in the instructions)
4. Change icon of preliminary from (X) to (?)
