### ISSUE TITLE
`Exam mode`: PDF summary broken and do not show the problem statement completely. 

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#8931]
### Describe the bug

PDF summary broken and do not show the problem statement completely. 

### To Reproduce

1. Solve an exam with different exercises 
2. Check the summary that the problem statement is cut and that the foot buttons are (in the middle of the page). Check the screenshot. 
3. Same when you export to PDF

### Expected behavior

The exercises should be adapted to the size of the PDF pages. 

### Screenshots

![image](https://github.com/ls1intum/Artemis/assets/88991954/cf32ec7f-19f8-43d0-a71d-bb1ab60a6f24)

### Which version of Artemis are you seeing the problem on?

7.3.0

### What browsers are you seeing the problem on?

Chrome

**Comment by florian-glombik** [comment]
Could you please add more concrete steps to reproduce @Santia-go?

For me the issue did not occur.

[examExportWastingSomeSpace.pdf](https://github.com/user-attachments/files/16049936/examExportWastingSomeSpace.pdf)

**Comment by Santia-go** [comment]
> Could you please add more concrete steps to reproduce @Santia-go?
> 
> For me, the issue did not occur: [examExportWastingSomeSpace.pdf](https://github.com/user-attachments/files/16049936/examExportWastingSomeSpace.pdf)

Those are the only steps for that issue. But maybe it is not there anymore because I tested on production instead of the newest release. Last week I also found a related problem with the PDF summary, but Stephan told me that this is already fixed in the coming release.

**Comment by krusche** [comment]
I'm not sure if all issues are already fixed. Unfortunately, printing PDFs with dynamically complex content is really difficult and you can always find edge cases. On my personal chrome instance on my Mac it still does not work based on the printer configuration, however @az108 and a few other developers reported that it works quite stable except edge cases

**Comment by janthoXO** [comment]
for the FPV mock exam the summary export only exports the first page of the exam. The remaining 4 exercises do not get printed.
[Funktionale Programmierung und Verifikation (SS24).pdf](https://github.com/user-attachments/files/16362162/Funktionale.Programmierung.und.Verifikation.SS24.pdf)

**Comment by krusche** [comment]
Reloading the page can help to print all pages

**Comment by ge94zec** [comment]
The issue is still present. The problem statement is still cut off, and the footer buttons are still positioned incorrectly, sometimes appearing in the middle of the page. This happens in the exported PDF when using the Chrome browser.


<img width="714" height="1020" alt="Image" src="https://github.com/user-attachments/assets/e0e0757d-3103-4314-82d7-e12eb05cc0af" />
<img width="644" height="877" alt="Image" src="https://github.com/user-attachments/assets/30d729ac-8c3a-408e-9d47-cd64bfb512b5" />
